---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Sarah Zhang (sz6753)

#### Introduction 

The two datasets that I chose are gpa_study_hours and satgpa which I obtained from https://vincentarelbundock.github.io/Rdatasets/datasets.html. The gpa_study_hours data set has 193 rows and 2 variables: gpa and study_hours. The gpa variable represents the grade point average of a college student and the study_hours variable represents the number of hours that student studies per week. The satgpa data set has 1000 rows and 6 variables: sex, sat_v, sat_m, sat_sum, hs_gpa, and fy_gpa. The sex variable represents the sex of a college student, the sat_v variable represents the verbal SAT percentile of that student, the sat_m variable represents the math SAT percentile of that student, the sat_sum variable represents the total of verbal and math SAT percentiles of that student, the hs_gpa variable represents the high school grade point average of that student, and the fy_gpa variable represents the first year (college) grade point average of that student. The data for the gpa_study_hours data set was collected through an anonymous survey from an introductory statistics course at a private US university. The data for the satgpa data set was collected through an educational testing service at an unnamed college. 

I chose these data sets because I was interested in seeing how the amount study hours a student spends is related to that student's SAT scores. I'm interested in this because I feel that I tend to study a lot and I would like to see if, in general, students who study more tend to have high test scores. Since both data sets have a gpa variable I will be joining them based on the gpa variable from the gpa_study_hours dataset and the fy_gpa variable from the satgpa data set. One association that I predict will occur is that students who study more often will have higher SAT scores. 

```{R}
library(tidyverse)
study_hours <- read_csv('gpa_study_hours.csv')
sat <- read_csv('satgpa.csv')
head(study_hours)
head(sat)
```

#### Tidying: Reshaping

The data sets are tidy already so this is just to demonstrate that I can reshape the data. First, I pivoted wider on the study_hours data set by using the gpas as the columns and the study_hours as the values. I also pivoted wider on the sat data set by using the sex as the columns and the sat_sum as the values. Then, I pivoted back longer on the study_hours data set by reverting the gpas and study_hours as their own separate columns and removed the NAs. I also pivoted back longer on the sat data set by reverting the sex and sat_sum as their own separate columns and removed the NAs.

```{R}
# pivot wider
study_hours <- study_hours %>% pivot_wider(names_from="gpa",values_from="study_hours")
sat <- sat %>% pivot_wider(names_from="sex",values_from="sat_sum")
head(study_hours)
head(sat)

# pivot longer
study_hours <- study_hours %>% pivot_longer(-1, names_to="gpa",values_to="study_hours", values_drop_na=T)
sat <- sat %>% pivot_longer(c("1", "2"), names_to="sex",values_to="sat_sum", values_drop_na=T)
head(study_hours)
head(sat)
```

    
#### Joining/Merging

```{R}
study_hours$gpa <- as.double(study_hours$gpa) 

joined <- study_hours %>% inner_join(sat, by=c("gpa"="fy_gpa"))
head(joined)
```

I performed an inner join on the two data sets because I wanted to only include the GPAs that were present in both data sets and didn't want there to be any rows with NAs. I matched the rows based on the gpa of the study_hours data set and the fy_gpa of the sat data set since they both represent the  GPAs of college students. I also had to convert the gpa column of the study_hours gpa to be type double so that it could match up with the fy_gpa column of the sat data set.

```{R}
nrow(study_hours)
nrow(sat)
nrow(distinct(study_hours, gpa))
nrow(distinct(sat, fy_gpa))
nrow(study_hours) - nrow(distinct(joined, X1.x))
nrow(sat) - nrow(distinct(joined, X1.y))
study_hours %>% anti_join(sat, by=c("gpa"="fy_gpa"))
sat %>% anti_join(study_hours, by=c("fy_gpa"="gpa"))
nrow(joined)
```

There was a total of 193 observations/rows in the study_hours data set and a total of 1000 observations/rows in the sat data set. There is a total of 63 distinct gpas (IDs) in the study_hours data set and a total of 282 distinct fy_gpas (IDs) in the sat data set. 42 gpas (IDs) in the study_hours data set do not appear in the sat data set and 871 fy_gpas (IDs) in the sat data set do not appear in the study_hours data set which are all shown in the anti joined data set above. 42 observations from the study_hours data set were dropped and 871 observations from the sat data set were dropped when the inner join was performed. The problem with this is that there is now less data (less gpas) to look at which might not allow our analysis to be as accurate. There is a total of 468 common gpas (IDs) in the joined data set (that appear in both the study_hours and sat data sets). The size of the joined data set is a lot larger that the study_hours data set probably because there were multiple observations in the sat data set for a gpa. The size of the joined data set is a lot smaller than the sat data set probably because a lot of the data had to be dropped since there wasn't a matching gpa in the study_hours data set.

####  Wrangling

```{R}
# mutate/create column to represent sex as a string
mutated_joined <- joined %>% mutate(sex_str = str_replace_all(sex, "[^1]", "Female"), )
mutated_joined <- mutated_joined %>% mutate(sex_str = str_replace_all(sex_str, "[^2a-zA-Z]", "Male"))

# mutate/create column to rank amount of study_hours (A as high amount of study hours and F as low amount of study hours)
mutated_joined <- mutated_joined %>% mutate(study_hours_tier = case_when(
                                      study_hours <= 10 ~ "F",
                                      study_hours <= 20 ~ "E",
                                      study_hours <= 30 ~ "D",
                                      study_hours <= 40 ~ "C",
                                      study_hours <= 50 ~ "B",
                                      TRUE ~ "A",
                                      ))
head(mutated_joined)
```
In the above code chunk, I mutated the joined data set to create two new columns: sex_str and study_hours_tier. The sex_str column is a string representation of the sex so 1 is represented as "Male" and 2 is represented as "Female". I used mutate to create the new column and used str_replace_all and regex to find the correct variables to replace. The study_hours_tiers represents the study_hours as rankings so a high amount of study_hours would be ranked 'A' and a low amount of study_hours would be ranked 'F'. I used mutate to create the column and case_when to create the  variables.

```{R}
# averages of sat scores and study hours for each gpa group
gpa_avgs <- mutated_joined %>% group_by(gpa) %>% summarize(avg_study_hours = mean(study_hours), avg_sat_sum=mean(sat_sum), avg_sat_v=mean(sat_v), avg_sat_m=mean(sat_m)) %>% arrange(-avg_study_hours)
head(gpa_avgs)

# average, median, and sd sat sum for each study hours ranking and each sex
study_hours_sat <- mutated_joined %>% group_by(study_hours_tier, sex_str) %>% summarize(avg_sat_sum=mean(sat_sum), med_sat_sum=median(sat_sum), sd_sat_sum=sd(sat_sum))
study_hours_sat_kabled <- study_hours_sat %>% knitr::kable(digits = 2, align = 'c', col.names=str_to_title(names(.)))
head(study_hours_sat)
head(study_hours_sat_kabled)
```
In the above code chunk, I first summarized the average study_hours, sat_sum, sat_v,and sat_m for each gpa grouping and then arranged them in descending order based on average study hours. Based on this table, so far, it seems that study_hours and sat scores don't have much of an association. I then summarized the average, median, and standard deviation sat_sum  for each study_hours ranking and for each sex. Based on this table, it also seems that study_hours and sat scores don't have much of an association. However, I did notice that males tend to have higher sat scores compared to females within the same study_hours ranking. I also noticed that there seems to be more variation in sat scores for lower ranking study_hours based on the sd_sat_sum column. Additionally, I applied kable to the second table to style it. 

```{R}
# number of occurrence of each sex and of each study hours ranking
sex_occ <- mutated_joined %>% group_by(sex_str) %>% summarize(occurences=n())
head(sex_occ)
study_hours_tier_occ <- mutated_joined %>% group_by(study_hours_tier) %>% summarize(occurences=n())
head(study_hours_tier_occ)

# number of NAs for each variable
joined %>% summarise_all(funs(sum(is.na(.))))
```
In the above code chunk, I summarized the frequencies of each level for the categorical variables (sex and study_hours_tier). I found that there are 261 Females and and 207 Males. Based on the study_hours rankings and their occurrences, there are 4 observations that study more than 50 hours per week, 2 observations that study 40-50 hours per week, 22 observations that study 30-40 hours per week, 71 observations that study 20-30 hours per week, 173 observations that study 10-20 hours per week, and 196 observations that study less than 10 hours per week. There were no NAs in any of the variables which makes sense since we performed an inner join before.

```{R}
# filter out females and select gpa that matched mine to compare study hours
my_sex_gpa <- mutated_joined %>% filter(sex_str=="Female" & gpa>=3.85 & gpa <=3.90) %>% select(study_hours, sat_sum)
head(my_sex_gpa)
```
In the above code chunk, I filtered out the females and the GPAs that closely matched mine and then selected the amount of study_hours they had. It was interesting to see that the study_hours varied quite a bit from each observation but the sat_sum was pretty similar with each other. I'd say that the amount of study_hours that I spend fall in the middle of these observations (around 14 hours per week). 

```{R}
# defined own function that calculates difference between verbal sat scores and math sat scores
my_function <- function(sat_v, sat_m) {
  sat_v - sat_m
}
sat_diff <- gpa_avgs %>% group_by(avg_study_hours) %>% summarize(avg_sat_diff=mean(my_function(avg_sat_v, avg_sat_m)))
head(sat_diff)
```
In the above code chunk, I created my own function to summarize with. The function I wrote calculates the difference between the verbal sat percentile and the math sat percentile. I summarized with this function to calculate the average verbal and math sat difference for each average amount of study_hours. From this table, it seems like the amount of study hours does not affect how well a student does on the verbal sat vs the math sat. I did notice that on average, students perform worse on the verbal sat compared to the math sat since most of the average differences are negative.

#### Visualizing

```{R}
joined %>% ggplot(aes(x=study_hours, y=sat_sum, color=sex)) + geom_point(size = 4, alpha = .5) + geom_smooth(method="lm") + scale_x_continuous(breaks=seq(0,60,5)) + scale_y_continuous(breaks=seq(50,150,5)) + ggtitle("Study Hours per Week vs Total SAT Percentile") + ylab("Total SAT Percentile") + xlab("Study Hours per Week") + theme_minimal()
```

In the above plot, I created a scatter plot using geom_point() and a line of best fit using geom_smooth() to compare the amount of study hours per week vs the total of verbal and math SAT percentiles. I also colored the points and line to be separated by sex. Based on this plot, there doesn't seem to be a relationship between the amount of study hours and SAT scores/percentiles since both lines look pretty horizontal and the points are randomly scattered for each sex. I did notice  that the line that represents males is higher than the line that represents females which might indicate that males usually have higher SAT scores/percentiles compared to females regardless of amount of time spent studying.

```{R}
mutated_joined %>% ggplot(aes(x=study_hours_tier, y=sat_sum, fill=study_hours_tier)) + geom_bar(stat="summary", alpha=0.5, fun=mean) + geom_errorbar(stat="summary", width=0.5) + scale_y_continuous(breaks=seq(0, 130, 10)) + ggtitle("Study Hours Ranking vs Average Total Sat Percentile") + ylab("Average Total Sat Percentile") + xlab("Study Hours Ranking") + theme(legend.position="none")
```

In the above plot, I created a bar plot representing the average SAT percentile for each study_hours ranking. I also added error bars for each ranking. Based on this plot, the average SAT percentile is pretty similar among each study  hours ranking which further shows that SAT  score is probably not related to the amount of study hours a student spends. Additionally, the error bars for each of the rankings are all pretty short which indicates that there is less variability in the data so it's pretty reliable.

```{R}
mutated_joined %>% ggplot(aes(x=sex_str, y=sat_sum, fill=sex_str)) + geom_bar(stat="summary", alpha=0.75, fun=mean) + geom_errorbar(stat="summary", width=0.5) + geom_point(stat="summary", fun=mean, color="red", size=4) + scale_y_continuous(breaks=seq(0, 130, 10)) + ggtitle("Sex vs Average Total Sat Percentile") + ylab("Average Total Sat Percentile") + xlab("Sex") + theme(legend.position="none")
```

In the above plot, I created a bar plot that represents the average SAT percentile for each sex. I also added error bars and a point to represent the average for each sex. Based on this plot, the average SAT percentile for males is higher than the average SAT percentile for females since the bar is higher. This might indicate that males generally have higher SAT scores/percentiles compared to females. Additionally, the error bars are very short which indicates that there is not much variability of the data within each sex so the data is reliable.

#### Concluding Remarks

If any!




